import type { LearningStage, LearningConcept } from '@/lib/types/learning';

export const LEARNING_STAGES: LearningStage[] = [
  {
    id: 'stage-1-identity',
    order: 1,
    name: 'Building Foundation',
    metaphor: 'Constructing a Secure Office Building',
    metaphorDescription: 'Every secure building starts with knowing who can enter. We\'ll build your identity foundation.',
    icon: '🏢',
    concepts: ['azure-ad', 'users-groups', 'rbac', 'managed-identities'],
    celebrationTitle: 'Foundation Complete!',
    celebrationMessage: 'You\'ve mastered the identity layer. Your building now has secure access control!',
  },
  {
    id: 'stage-2-security',
    order: 2,
    name: 'Security Layer',
    metaphor: 'Office Security Checkpoint',
    metaphorDescription: 'Now that people can enter, let\'s add smart security systems to protect your resources.',
    icon: '🔐',
    concepts: ['conditional-access', 'pim', 'key-vault', 'defender'],
    celebrationTitle: 'Security Champion!',
    celebrationMessage: 'Your building is now protected with enterprise-grade security systems!',
  },
  {
    id: 'stage-3-networking',
    order: 3,
    name: 'Infrastructure',
    metaphor: 'City Transportation System',
    metaphorDescription: 'Time to build the roads and traffic systems that connect everything together.',
    icon: '🌐',
    concepts: ['vnets', 'subnets', 'nsgs', 'azure-firewall', 'load-balancer'],
    celebrationTitle: 'Network Architect!',
    celebrationMessage: 'You\'ve built a complete network infrastructure. Traffic flows securely!',
  },
  {
    id: 'stage-4-compute',
    order: 4,
    name: 'Operations',
    metaphor: 'Factory Production Line',
    metaphorDescription: 'With infrastructure ready, let\'s add the workstations and storage that power your applications.',
    icon: '⚙️',
    concepts: ['virtual-machines', 'scale-sets', 'app-service', 'storage-accounts', 'cosmos-db'],
    celebrationTitle: 'Operations Master!',
    celebrationMessage: 'Your factory is running! Compute and storage are ready for production.',
  },
  {
    id: 'stage-5-monitoring',
    order: 5,
    name: 'Observability',
    metaphor: 'Security Camera Network',
    metaphorDescription: 'Finally, let\'s add the monitoring systems to watch over everything you\'ve built.',
    icon: '📊',
    concepts: ['azure-monitor', 'log-analytics', 'alerts', 'application-insights'],
    celebrationTitle: 'Azure Administrator Ready!',
    celebrationMessage: 'Congratulations! You\'ve mastered all the core concepts. You\'re ready for the AZ-104!',
  },
];

export const LEARNING_CONCEPTS: LearningConcept[] = [
  {
    id: 'azure-ad',
    stageId: 'stage-1-identity',
    order: 1,
    name: 'Microsoft Entra ID',
    icon: '🚪',
    metaphor: 'The Front Door',
    hookSentence: 'Every building needs a front door. Microsoft Entra ID is your cloud\'s secure entrance.',
    whyYouNeed: 'Without identity management, anyone could access your resources. Entra ID ensures only the right people get in.',
    realWorldExample: 'Just like a hotel reception desk verifies guests before giving room keys, Entra ID verifies users before granting access to Azure resources.',
    howToUse: [
      'Create your Entra ID tenant (your building\'s address)',
      'Add users (register your employees)',
      'Configure authentication methods (set up the door locks)',
    ],
    technicalDetails: 'Microsoft Entra ID (formerly Azure Active Directory) is a cloud-based identity and access management service. It provides single sign-on, multi-factor authentication, and conditional access policies.',
    prerequisites: [],
    visualElement: 'door',
    actionButtonText: 'Add the front door',
  },
  {
    id: 'users-groups',
    stageId: 'stage-1-identity',
    order: 2,
    name: 'Users & Groups',
    icon: '👥',
    metaphor: 'Employee Badges',
    hookSentence: 'Badges identify who works here. Users and Groups organize your people.',
    whyYouNeed: 'Managing permissions individually is chaos. Groups let you organize users and assign permissions efficiently.',
    realWorldExample: 'Like color-coded badges in an office - blue for engineering, green for sales - groups categorize users for easier management.',
    howToUse: [
      'Create user accounts for each person',
      'Organize users into logical groups',
      'Assign permissions to groups, not individuals',
    ],
    technicalDetails: 'Users represent individual identities. Groups can be Security groups (for permissions) or Microsoft 365 groups (for collaboration). Dynamic groups auto-populate based on user attributes.',
    prerequisites: ['azure-ad'],
    visualElement: 'badges',
    actionButtonText: 'Create employee badges',
  },
  {
    id: 'rbac',
    stageId: 'stage-1-identity',
    order: 3,
    name: 'Role-Based Access Control',
    icon: '🔑',
    metaphor: 'The Key System',
    hookSentence: 'Different keys open different doors. RBAC controls who can do what.',
    whyYouNeed: 'Not everyone should have the master key. RBAC ensures people only access what they need for their job.',
    realWorldExample: 'A janitor has keys to cleaning closets, but not the CEO\'s office. RBAC works the same way - roles define access levels.',
    howToUse: [
      'Identify what actions users need to perform',
      'Choose the appropriate built-in role',
      'Assign the role at the right scope (subscription, resource group, or resource)',
    ],
    technicalDetails: 'RBAC uses role assignments combining a security principal (who), role definition (what they can do), and scope (where). Built-in roles include Owner, Contributor, Reader, and many specialized roles.',
    prerequisites: ['azure-ad', 'users-groups'],
    visualElement: 'keys',
    actionButtonText: 'Set up the key system',
  },
  {
    id: 'managed-identities',
    stageId: 'stage-1-identity',
    order: 4,
    name: 'Managed Identities',
    icon: '🤖',
    metaphor: 'Robot Employees',
    hookSentence: 'Some workers are automated. Managed Identities give your apps their own secure identity.',
    whyYouNeed: 'Apps need to access resources too, but storing passwords in code is dangerous. Managed Identities solve this securely.',
    realWorldExample: 'Like giving a delivery robot its own badge instead of sharing a human\'s credentials - it\'s trackable and revocable.',
    howToUse: [
      'Enable managed identity on your Azure resource',
      'Grant the identity access to target resources',
      'Your app authenticates automatically - no passwords needed',
    ],
    technicalDetails: 'System-assigned identities are tied to a resource lifecycle. User-assigned identities can be shared across resources. Both eliminate credential management in code.',
    prerequisites: ['azure-ad', 'rbac'],
    visualElement: 'robot',
    actionButtonText: 'Activate robot employees',
  },
  {
    id: 'conditional-access',
    stageId: 'stage-2-security',
    order: 1,
    name: 'Conditional Access',
    icon: '🔍',
    metaphor: 'Smart Security Scanner',
    hookSentence: 'A smart scanner that checks more than just your badge. Context matters.',
    whyYouNeed: 'A valid password isn\'t enough. You need to verify the device, location, and risk level before granting access.',
    realWorldExample: 'Like airport security that checks your ticket, ID, and scans your bags - multiple checks for higher security.',
    howToUse: [
      'Define conditions (who, from where, which app)',
      'Set access controls (allow, block, require MFA)',
      'Test with report-only mode before enforcing',
    ],
    technicalDetails: 'Conditional Access policies evaluate signals like user, device, location, and real-time risk. Actions include requiring MFA, compliant devices, or blocking access entirely.',
    prerequisites: ['azure-ad', 'users-groups'],
    visualElement: 'scanner',
    actionButtonText: 'Install the smart scanner',
  },
  {
    id: 'pim',
    stageId: 'stage-2-security',
    order: 2,
    name: 'Privileged Identity Management',
    icon: '⏰',
    metaphor: 'Time-Locked Executive Elevator',
    hookSentence: 'The executive elevator only works when you really need it. Just-in-time access.',
    whyYouNeed: 'Standing admin access is risky. PIM provides elevated permissions only when needed, with approval and time limits.',
    realWorldExample: 'Like a bank vault that requires two keys and only opens during business hours - multiple safeguards for sensitive access.',
    howToUse: [
      'Configure eligible role assignments',
      'Set activation requirements (approval, MFA, justification)',
      'Users activate roles when needed, for limited time',
    ],
    technicalDetails: 'PIM enables just-in-time privileged access, enforces approval workflows, and provides audit trails. Supports both Entra ID roles and Azure resource roles.',
    prerequisites: ['azure-ad', 'rbac'],
    visualElement: 'elevator',
    actionButtonText: 'Set up the executive elevator',
  },
  {
    id: 'key-vault',
    stageId: 'stage-2-security',
    order: 3,
    name: 'Azure Key Vault',
    icon: '🔒',
    metaphor: 'Safe Deposit Boxes',
    hookSentence: 'Your most valuable secrets deserve a vault. Key Vault protects them.',
    whyYouNeed: 'Passwords, certificates, and API keys in code or config files are vulnerable. Key Vault centralizes and protects secrets.',
    realWorldExample: 'Like a bank\'s safe deposit boxes - only authorized people can access specific boxes, with full audit trails.',
    howToUse: [
      'Create a Key Vault in your subscription',
      'Store secrets, keys, or certificates',
      'Grant access using RBAC or access policies',
    ],
    technicalDetails: 'Key Vault stores secrets, cryptographic keys, and certificates. Supports HSM-backed keys for highest security. Integrates with managed identities for passwordless access.',
    prerequisites: ['azure-ad', 'rbac'],
    visualElement: 'vault',
    actionButtonText: 'Install the vault',
  },
  {
    id: 'defender',
    stageId: 'stage-2-security',
    order: 4,
    name: 'Microsoft Defender for Cloud',
    icon: '🛡️',
    metaphor: 'Security Guard Team',
    hookSentence: 'A team of guards constantly watching for threats. Defender protects your cloud.',
    whyYouNeed: 'Threats evolve constantly. Defender provides continuous security assessment and threat protection across your resources.',
    realWorldExample: 'Like a security team that patrols, monitors cameras, and responds to incidents - proactive protection.',
    howToUse: [
      'Enable Defender for Cloud on your subscription',
      'Review security recommendations',
      'Enable enhanced protections for specific resource types',
    ],
    technicalDetails: 'Defender for Cloud provides security posture management (CSPM) and workload protection (CWP). Includes secure score, recommendations, and threat detection across Azure, hybrid, and multi-cloud.',
    prerequisites: ['azure-ad'],
    visualElement: 'shield',
    actionButtonText: 'Hire the security team',
  },
  {
    id: 'vnets',
    stageId: 'stage-3-networking',
    order: 1,
    name: 'Virtual Networks',
    icon: '🏘️',
    metaphor: 'Neighborhood Districts',
    hookSentence: 'Every city has neighborhoods. VNets are your cloud\'s private districts.',
    whyYouNeed: 'Resources need a private space to communicate securely. VNets provide isolated network environments.',
    realWorldExample: 'Like gated communities in a city - residents can interact freely inside, but outsiders need permission to enter.',
    howToUse: [
      'Define your address space (the neighborhood boundaries)',
      'Create subnets for different purposes',
      'Deploy resources into appropriate subnets',
    ],
    technicalDetails: 'VNets provide network isolation using private IP address spaces. Support peering for VNet-to-VNet connectivity, and VPN/ExpressRoute for hybrid connectivity.',
    prerequisites: [],
    visualElement: 'neighborhood',
    actionButtonText: 'Draw the neighborhood',
  },
  {
    id: 'subnets',
    stageId: 'stage-3-networking',
    order: 2,
    name: 'Subnets',
    icon: '🏠',
    metaphor: 'City Blocks',
    hookSentence: 'Neighborhoods have blocks. Subnets organize your network into logical sections.',
    whyYouNeed: 'Different resources have different security needs. Subnets let you segment and apply different rules.',
    realWorldExample: 'Like separating residential, commercial, and industrial zones - each has different rules and access patterns.',
    howToUse: [
      'Plan your subnet address ranges',
      'Create subnets for web, app, and data tiers',
      'Associate network security groups for protection',
    ],
    technicalDetails: 'Subnets divide VNet address space. Each subnet can have its own NSG and route table. Some services require dedicated subnets (like Azure Firewall, Application Gateway).',
    prerequisites: ['vnets'],
    visualElement: 'blocks',
    actionButtonText: 'Create city blocks',
  },
  {
    id: 'nsgs',
    stageId: 'stage-3-networking',
    order: 3,
    name: 'Network Security Groups',
    icon: '🚦',
    metaphor: 'Traffic Lights',
    hookSentence: 'Traffic lights control the flow. NSGs control network traffic.',
    whyYouNeed: 'Not all traffic should flow freely. NSGs filter traffic based on source, destination, and port.',
    realWorldExample: 'Just like traffic lights prevent accidents at intersections, NSGs prevent unauthorized network access.',
    howToUse: [
      'Create an NSG with inbound and outbound rules',
      'Associate it with subnets or network interfaces',
      'Rules are evaluated by priority (lowest number = highest priority)',
    ],
    technicalDetails: 'NSGs contain security rules with priority, source/destination, port, and action (allow/deny). Default rules allow VNet and load balancer traffic, deny internet inbound.',
    prerequisites: ['vnets', 'subnets'],
    visualElement: 'trafficlight',
    actionButtonText: 'Install traffic lights',
  },
  {
    id: 'azure-firewall',
    stageId: 'stage-3-networking',
    order: 4,
    name: 'Azure Firewall',
    icon: '🏰',
    metaphor: 'Central Traffic Control Tower',
    hookSentence: 'The control tower sees all traffic. Azure Firewall is your network\'s command center.',
    whyYouNeed: 'NSGs work at the subnet level. Firewall provides centralized, stateful inspection across your entire network.',
    realWorldExample: 'Like an air traffic control tower that monitors and directs all flights - centralized visibility and control.',
    howToUse: [
      'Deploy Azure Firewall in a hub VNet',
      'Create application and network rules',
      'Route traffic through the firewall using UDRs',
    ],
    technicalDetails: 'Azure Firewall is a managed, stateful firewall. Supports FQDN filtering, threat intelligence, and TLS inspection. Integrates with Azure Monitor for logging.',
    prerequisites: ['vnets', 'subnets'],
    visualElement: 'tower',
    actionButtonText: 'Build the control tower',
  },
  {
    id: 'load-balancer',
    stageId: 'stage-3-networking',
    order: 5,
    name: 'Load Balancer',
    icon: '⚖️',
    metaphor: 'Traffic Distributor',
    hookSentence: 'Distribute the load evenly. Load Balancer ensures no single server gets overwhelmed.',
    whyYouNeed: 'One server can\'t handle everything. Load balancing distributes traffic for reliability and performance.',
    realWorldExample: 'Like multiple checkout lanes at a store - customers are directed to available cashiers to reduce wait times.',
    howToUse: [
      'Create a load balancer (public or internal)',
      'Configure backend pool with your VMs',
      'Set up health probes and load balancing rules',
    ],
    technicalDetails: 'Azure Load Balancer operates at Layer 4 (TCP/UDP). Supports inbound and outbound scenarios, availability zones, and HA ports. Application Gateway provides Layer 7 load balancing.',
    prerequisites: ['vnets'],
    visualElement: 'scale',
    actionButtonText: 'Set up the distributor',
  },
  {
    id: 'virtual-machines',
    stageId: 'stage-4-compute',
    order: 1,
    name: 'Virtual Machines',
    icon: '💻',
    metaphor: 'Workstations',
    hookSentence: 'Every factory needs workstations. VMs are your cloud computers.',
    whyYouNeed: 'You need compute power to run applications. VMs provide flexible, scalable virtual computers.',
    realWorldExample: 'Like renting office space with desks and computers - you get what you need without buying hardware.',
    howToUse: [
      'Choose your VM size (CPU, memory, storage)',
      'Select an operating system image',
      'Configure networking and deploy',
    ],
    technicalDetails: 'VMs offer IaaS compute with full OS control. Size families optimize for compute, memory, storage, or GPU. Support availability sets and zones for high availability.',
    prerequisites: ['vnets', 'nsgs'],
    visualElement: 'computer',
    actionButtonText: 'Set up workstations',
  },
  {
    id: 'scale-sets',
    stageId: 'stage-4-compute',
    order: 2,
    name: 'Virtual Machine Scale Sets',
    icon: '📈',
    metaphor: 'Modular Production Lines',
    hookSentence: 'Add more lines when demand increases. Scale Sets grow automatically.',
    whyYouNeed: 'Manual scaling is slow and error-prone. Scale Sets automatically adjust capacity based on demand.',
    realWorldExample: 'Like a factory that adds production lines during holiday rush and removes them after - elastic capacity.',
    howToUse: [
      'Create a scale set with a base VM configuration',
      'Configure autoscale rules (CPU, memory, schedule)',
      'Scale Sets handle the rest automatically',
    ],
    technicalDetails: 'VMSS manages groups of identical VMs. Supports autoscaling, rolling upgrades, and availability zones. Integrates with Load Balancer for traffic distribution.',
    prerequisites: ['virtual-machines', 'load-balancer'],
    visualElement: 'factory',
    actionButtonText: 'Build production lines',
  },
  {
    id: 'app-service',
    stageId: 'stage-4-compute',
    order: 3,
    name: 'App Service',
    icon: '🚀',
    metaphor: 'Managed Assembly Line',
    hookSentence: 'Focus on your product, not the machinery. App Service handles the infrastructure.',
    whyYouNeed: 'Managing VMs is overhead. App Service lets you deploy code without worrying about servers.',
    realWorldExample: 'Like a contract manufacturer - you provide the design, they handle production, quality control, and shipping.',
    howToUse: [
      'Create an App Service Plan (the factory floor)',
      'Create a Web App (your product line)',
      'Deploy your code via Git, CI/CD, or upload',
    ],
    technicalDetails: 'App Service is a PaaS offering for web apps, APIs, and mobile backends. Supports .NET, Java, Node.js, Python, PHP. Includes deployment slots, custom domains, and SSL.',
    prerequisites: ['vnets'],
    visualElement: 'rocket',
    actionButtonText: 'Launch the assembly line',
  },
  {
    id: 'storage-accounts',
    stageId: 'stage-4-compute',
    order: 4,
    name: 'Storage Accounts',
    icon: '📦',
    metaphor: 'Warehouse System',
    hookSentence: 'Every factory needs a warehouse. Storage Accounts hold your data.',
    whyYouNeed: 'Applications generate data. Storage Accounts provide durable, scalable storage for files, blobs, queues, and tables.',
    realWorldExample: 'Like a warehouse with different sections - cold storage for archives, quick-access shelves for active inventory.',
    howToUse: [
      'Create a storage account with appropriate redundancy',
      'Choose the right storage type (Blob, File, Queue, Table)',
      'Configure access tiers based on usage patterns',
    ],
    technicalDetails: 'Storage Accounts offer Blob (objects), File (SMB shares), Queue (messaging), and Table (NoSQL) storage. Redundancy options: LRS, ZRS, GRS, GZRS. Access tiers: Hot, Cool, Archive.',
    prerequisites: [],
    visualElement: 'warehouse',
    actionButtonText: 'Build the warehouse',
  },
  {
    id: 'cosmos-db',
    stageId: 'stage-4-compute',
    order: 5,
    name: 'Cosmos DB',
    icon: '🌍',
    metaphor: 'Global Inventory System',
    hookSentence: 'Inventory available worldwide, instantly. Cosmos DB is globally distributed.',
    whyYouNeed: 'Global applications need global data. Cosmos DB replicates data across regions with low latency.',
    realWorldExample: 'Like a retail chain with synchronized inventory across all stores worldwide - always accurate, always fast.',
    howToUse: [
      'Create a Cosmos DB account with your preferred API',
      'Choose consistency level based on your needs',
      'Configure geo-replication for global distribution',
    ],
    technicalDetails: 'Cosmos DB is a globally distributed, multi-model database. Supports SQL, MongoDB, Cassandra, Gremlin, and Table APIs. Offers five consistency levels from strong to eventual.',
    prerequisites: ['storage-accounts'],
    visualElement: 'globe',
    actionButtonText: 'Deploy global inventory',
  },
  {
    id: 'azure-monitor',
    stageId: 'stage-5-monitoring',
    order: 1,
    name: 'Azure Monitor',
    icon: '📺',
    metaphor: 'Central Monitoring Station',
    hookSentence: 'See everything from one screen. Azure Monitor is your control room.',
    whyYouNeed: 'You can\'t fix what you can\'t see. Azure Monitor collects and analyzes telemetry from all your resources.',
    realWorldExample: 'Like a security control room with screens showing every camera feed - complete visibility.',
    howToUse: [
      'Azure Monitor is enabled by default for most resources',
      'Configure diagnostic settings to collect detailed logs',
      'Create dashboards to visualize key metrics',
    ],
    technicalDetails: 'Azure Monitor collects metrics and logs from Azure resources, applications, and infrastructure. Includes Metrics Explorer, Log Analytics, and Workbooks for visualization.',
    prerequisites: [],
    visualElement: 'monitors',
    actionButtonText: 'Enter the control room',
  },
  {
    id: 'log-analytics',
    stageId: 'stage-5-monitoring',
    order: 2,
    name: 'Log Analytics',
    icon: '🔎',
    metaphor: 'Investigation Center',
    hookSentence: 'Dig deep into the data. Log Analytics finds the answers.',
    whyYouNeed: 'Metrics show what\'s happening now. Logs tell you why and help you investigate issues.',
    realWorldExample: 'Like a detective\'s evidence room - all the clues organized and searchable for investigation.',
    howToUse: [
      'Create a Log Analytics workspace',
      'Connect data sources (VMs, apps, Azure resources)',
      'Query logs using Kusto Query Language (KQL)',
    ],
    technicalDetails: 'Log Analytics workspaces store log data. KQL enables powerful queries across tables. Supports data retention policies and export to storage or Event Hubs.',
    prerequisites: ['azure-monitor'],
    visualElement: 'magnifier',
    actionButtonText: 'Set up investigations',
  },
  {
    id: 'alerts',
    stageId: 'stage-5-monitoring',
    order: 3,
    name: 'Alerts',
    icon: '🚨',
    metaphor: 'Alarm System',
    hookSentence: 'Get notified when something\'s wrong. Alerts are your early warning system.',
    whyYouNeed: 'You can\'t watch dashboards 24/7. Alerts notify you automatically when thresholds are breached.',
    realWorldExample: 'Like smoke detectors and burglar alarms - they watch constantly and alert you to problems.',
    howToUse: [
      'Define alert conditions (metric thresholds or log queries)',
      'Create action groups (email, SMS, webhook, automation)',
      'Configure alert rules to connect conditions and actions',
    ],
    technicalDetails: 'Alert rules evaluate conditions against metrics or logs. Action groups define notification channels and automated responses. Supports severity levels and alert suppression.',
    prerequisites: ['azure-monitor', 'log-analytics'],
    visualElement: 'alarm',
    actionButtonText: 'Install the alarms',
  },
  {
    id: 'application-insights',
    stageId: 'stage-5-monitoring',
    order: 4,
    name: 'Application Insights',
    icon: '🔬',
    metaphor: 'Product Quality Lab',
    hookSentence: 'Test your products continuously. Application Insights monitors app performance.',
    whyYouNeed: 'Infrastructure metrics aren\'t enough. You need to see how your application performs from the user\'s perspective.',
    realWorldExample: 'Like a quality control lab that tests products off the assembly line - catching defects before customers do.',
    howToUse: [
      'Add the Application Insights SDK to your app',
      'Configure connection string in your application',
      'View performance, failures, and user analytics',
    ],
    technicalDetails: 'Application Insights provides APM for web applications. Tracks requests, dependencies, exceptions, and custom events. Includes smart detection, availability tests, and user analytics.',
    prerequisites: ['azure-monitor'],
    visualElement: 'microscope',
    actionButtonText: 'Open the quality lab',
  },
];

export const STAGE_VISUAL_ELEMENTS: Record<string, string[]> = {
  'stage-1-identity': ['building-outline', 'door', 'badges', 'keys', 'robot'],
  'stage-2-security': ['scanner', 'elevator', 'vault', 'shield'],
  'stage-3-networking': ['neighborhood', 'blocks', 'trafficlight', 'tower', 'scale'],
  'stage-4-compute': ['computer', 'factory', 'rocket', 'warehouse', 'globe'],
  'stage-5-monitoring': ['monitors', 'magnifier', 'alarm', 'microscope'],
};
